[package]
name = "ambiguities"
version = "0.1.0"
authors = ["Konrad Siek <konrad.siek@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = {version = "0.18.1", features = ["lexer"]}

[dependencies]
lalrpop-util = "0.18.1"
regex = "1"
